version: '3.8'
services:
  app:
    image: leandrojpg/minha-aplicacao-nova:${IMAGE_TAG}
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: overlay
