version: "3.9"

services:
  redis:
    image: 34.150.128.51/lab/redis:alpine
    networks:
      - frontend

  db:
    image: 34.150.128.51/lab/postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 5000:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend

  vote2:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 5002:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result3:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 5003:80
    networks:
      - backend

  vote4:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 5004:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result5:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 5005:80
    networks:
      - backend    

  vote6:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 5006:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result7:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 5007:80
    networks:
      - backend

networks:
  frontend:
    name: stack1_frontend
  backend:
    name: stack1_backend

volumes:
  db-data:
