version: "3.9"

services:
  redis:
    image: 34.150.128.51/lab/redis:alpine
    networks:
      - frontend

  db:
    image: 34.150.128.51/lab/postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 6000:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 6001:80
    networks:
      - backend

  vote2:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 6002:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result3:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 6003:80
    networks:
      - backend

  vote4:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 6004:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result5:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 6005:80
    networks:
      - backend    

  vote6:
    image: 34.150.128.51/lab/examplevotingapp_vote
    ports:
      - 6006:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result7:
    image: 34.150.128.51/lab/examplevotingapp_result
    ports:
      - 6007:80
    networks:
      - backend

networks:
  frontend:
    name: stack2_frontend
  backend:
    name: stack2_backend

volumes:
  db-data:
